name: Build Desktop Installers

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'package.json'
      - 'forge.config.js'
      - '!src/site/**'
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node 22 LTS
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci
        working-directory: VirtualOS

      - name: Make installers
        run: npm run make
        working-directory: VirtualOS

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: installers-${{ runner.os }}
          path: VirtualOS/out/make/**
