name: Deploy Site (Simple)

on:
  # Disabled - using main deploy.yml instead
  # push:
  #   branches: [ main ]
  #   paths:
  #     - 'src/site/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./src/site
        cname: # Optional: add your custom domain here
